// Banco de perguntas do dia. Os dois respondem e so entao veem a resposta do outro.
module.exports = [
  'Qual foi a melhor parte do seu dia hoje?',
  'O que voce mais sente falta de fazer comigo pessoalmente?',
  'Qual musica te lembra de mim essa semana?',
  'Que coisa pequena eu faco que te deixa bem?',
  'Se a gente tivesse um domingo inteiro junto, o que faria?',
  'Qual medo voce tem sobre o nosso futuro e nunca falou em voz alta?',
  'O que voce quer estar fazendo daqui a cinco anos?',
  'Qual foi a ultima vez que eu te fiz rir de verdade?',
  'Que habito seu voce gostaria de mudar esse ano?',
  'Como voce prefere ser consolado quando esta mal?',
  'Qual lugar do mundo voce quer conhecer comigo primeiro?',
  'O que te deixou orgulhoso de si mesmo essa semana?',
  'Qual foi a coisa mais dificil da sua semana?',
  'Que tipo de casa voce imagina pra gente?',
  'O que voce aprendeu com o seu ultimo relacionamento?',
  'Qual comida voce quer que eu faca pra voce quando a gente se ver?',
  'Do que voce mais tem orgulho em mim?',
  'Que assunto voce evita falar comigo e por que?',
  'Qual foi o momento em que voce percebeu que gostava de mim?',
  'O que te daria mais seguranca na nossa relacao hoje?',
  'Qual sonho seu nao depende de mais ninguem?',
  'Como estao suas contas e seus planos de dinheiro esse mes?',
  'Que filme ou serie marcou voce e por que?',
  'O que voce faria se ganhasse um mes de folga total?',
  'Qual conselho voce daria pra voce de tres anos atras?',
  'Como voce quer comemorar nosso proximo aniversario de namoro?',
  'Que parte da minha rotina voce gostaria de conhecer melhor?',
  'Qual foi a ultima coisa que te emocionou?',
  'O que voce precisa de mim nessa semana especifica?',
  'Se a distancia acabasse amanha, qual seria o primeiro plano?',
  'Qual defeito seu voce acha que eu aguento bem demais?',
  'O que voce gostaria que a gente fizesse mais por chamada?',
  'Qual lembranca nossa voce mais repete na cabeca?',
  'O que voce quer aprender esse ano?',
  'Como esta sua relacao com a sua familia hoje?',
  'Que promessa voce quer fazer pra gente e cumprir?',
  'Qual foi a decisao mais corajosa que voce ja tomou?',
  'O que te cansa e voce nao costuma dizer?',
  'Qual seria o nosso dia perfeito se dinheiro nao fosse problema?',
  'O que voce quer que eu saiba e ainda nao te perguntei?',
];
